"""The two storage roots and the managed layout (tech-stack.md §15, decision 2026-09-25).

The user-selected library root holds the authoritative database and every managed byte, so a
library can be backed up or moved as one folder. Machine-local state (`%LOCALAPPDATA%/<App>`) holds
only derived or disposable data. Paths are ID-oriented, never Person- or name-oriented
(IMPLEMENTATION_ARCHITECTURE.md §16.3).

A storage key is a relative POSIX path under the library root, e.g. `originals/<artifact-id>`. It
is what `artifacts.storage_key` records; nothing outside this package turns one into a path.
"""

import re
from dataclasses import dataclass
from pathlib import Path

LIBRARY_DIRECTORIES = (
    "database",
    "originals",
    "crops",
    "thumbnails",
    "models",
    "derived",
    "backups",
    "recovery",
    # Same volume as the managed directories, so the final rename is atomic (decision 2026-09-25).
    "staging",
)
LOCAL_STATE_DIRECTORIES = ("indexes", "cache", "temp", "logs", "runtime", "installation")

# Top-level directories a storage key may name: the ones holding managed, artifact-backed bytes.
MANAGED_DIRECTORIES = frozenset({"originals", "crops", "thumbnails", "models"})

# Exactly the form `storage_key_for` generates: `<managed directory>/<32 lower-case hex>`. Anything
# else is refused outright, which leaves no room for Windows aliasing (trailing dots or spaces,
# case, device names such as NUL, alternate data streams, 8.3 names, UNC or drive prefixes).
_KEY = re.compile("(" + "|".join(sorted(MANAGED_DIRECTORIES)) + r")/([0-9a-f]{32})")


class UnsafeStorageKeyError(ValueError):
    """A storage key that is malformed or would resolve outside the managed directories."""


@dataclass(frozen=True)
class StorageRoots:
    library_root: Path
    local_state_root: Path

    @property
    def database_path(self) -> Path:
        return self.library_root / "database" / "library.db"

    @property
    def staging(self) -> Path:
        return self.library_root / "staging"

    def ensure_layout(self) -> None:
        """Create every directory of both roots. Idempotent; never removes anything."""
        for name in LIBRARY_DIRECTORIES:
            (self.library_root / name).mkdir(parents=True, exist_ok=True)
        for name in LOCAL_STATE_DIRECTORIES:
            (self.local_state_root / name).mkdir(parents=True, exist_ok=True)

    def path_for(self, storage_key: str) -> Path:
        """The absolute path for a storage key, refusing anything outside the managed directories.

        Keys are generated by this package, but they are read back from the database, so they are
        validated every time rather than trusted.
        """
        match = _KEY.fullmatch(storage_key)
        if match is None:
            raise UnsafeStorageKeyError(f"not a managed storage key: {storage_key!r}")
        directory, name = match.groups()
        path = self.library_root / directory / name
        # The managed directory itself could be a junction or symlink; the resolved file must
        # still sit in the real `<library>/<directory>`, not merely somewhere in the library.
        try:
            escaped = path.resolve().parent != self.library_root.resolve() / directory
        except (OSError, RuntimeError) as error:  # RuntimeError: a junction/symlink loop
            raise UnsafeStorageKeyError(f"cannot resolve {storage_key!r}: {error}") from error
        if escaped:
            raise UnsafeStorageKeyError(f"storage key escapes its directory: {storage_key!r}")
        return path

    def key_for(self, path: Path) -> str:
        """The storage key for a path inside the managed directories (the inverse of path_for)."""
        return path.relative_to(self.library_root).as_posix()
