"""The two storage roots and the managed layout (tech-stack.md §15, decision 2026-09-25).

The user-selected library root holds the authoritative database and every managed byte, so a
library can be backed up or moved as one folder. Machine-local state (`%LOCALAPPDATA%/<App>`) holds
only derived or disposable data. Paths are ID-oriented, never Person- or name-oriented
(IMPLEMENTATION_ARCHITECTURE.md §16.3).

A storage key is a relative POSIX path under the library root, e.g. `originals/<artifact-id>`. It
is what `artifacts.storage_key` records; nothing outside this package turns one into a path.
"""

from dataclasses import dataclass
from pathlib import Path, PurePosixPath

LIBRARY_DIRECTORIES = (
    "database",
    "originals",
    "crops",
    "thumbnails",
    "models",
    "derived",
    "backups",
    "recovery",
    # Same volume as the managed directories, so the final rename is atomic (decision 2026-09-25).
    "staging",
)
LOCAL_STATE_DIRECTORIES = ("indexes", "cache", "temp", "logs", "runtime", "installation")

# Top-level directories a storage key may name: the ones holding managed, artifact-backed bytes.
MANAGED_DIRECTORIES = frozenset({"originals", "crops", "thumbnails", "models"})


class UnsafeStorageKeyError(ValueError):
    """A storage key that is malformed or would resolve outside the managed directories."""


@dataclass(frozen=True)
class StorageRoots:
    library_root: Path
    local_state_root: Path

    @property
    def database_path(self) -> Path:
        return self.library_root / "database" / "library.db"

    @property
    def staging(self) -> Path:
        return self.library_root / "staging"

    def ensure_layout(self) -> None:
        """Create every directory of both roots. Idempotent; never removes anything."""
        for name in LIBRARY_DIRECTORIES:
            (self.library_root / name).mkdir(parents=True, exist_ok=True)
        for name in LOCAL_STATE_DIRECTORIES:
            (self.local_state_root / name).mkdir(parents=True, exist_ok=True)

    def path_for(self, storage_key: str) -> Path:
        """The absolute path for a storage key, refusing anything outside the managed directories.

        Keys are generated by this package, but they are read back from the database, so they are
        validated every time rather than trusted.
        """
        key = PurePosixPath(storage_key)
        parts = key.parts
        if (
            not storage_key
            or "\\" in storage_key
            or ":" in storage_key
            or key.as_posix() != storage_key  # canonical only: no "./", "//" or trailing "/"
            or key.is_absolute()
            or len(parts) < 2
            or parts[0] not in MANAGED_DIRECTORIES
            or any(part in ("", ".", "..") for part in parts)
        ):
            raise UnsafeStorageKeyError(f"not a managed storage key: {storage_key!r}")
        path = self.library_root.joinpath(*parts)
        if not path.resolve().is_relative_to(self.library_root.resolve()):
            raise UnsafeStorageKeyError(f"storage key escapes the library root: {storage_key!r}")
        return path

    def key_for(self, path: Path) -> str:
        """The storage key for a path inside the managed directories (the inverse of path_for)."""
        return path.relative_to(self.library_root).as_posix()
